# Example docker-compose for running this project in docker!
version: '3.3'

services:
  auth-server:
    image: auth-server:latest
    container_name: auth-server
    networks:
      - auth
    ports:
      - 8080:8080
    volumes:
      - path/to/certs:/app/certs
    environment:
      DATABASE_URL: postgres://${MASTER_USER}:${MASTER_PASS}@auth-postgres/${DATABASE_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      FROM_EMAIL: ${FROM_EMAIL}
      SMTP_KEY: "${SMTP_KEY}"
      TWO_FACTOR_KEY: "${TWO_FACTOR_KEY}"
      SMTP_ENCRYPTION_KEY: "${SMTP_ENCRYPTION_KEY}"
      LOG_KEY: "${LOG_KEY}"
      REDIRECT_URL: ${REDIRECT_URL}
      REDIS_CONNECTION_STRING: "redis://auth-redis:6379"
      ADMIN_KEY: "${ADMIN_KEY}"
      APP_NAME: "${APP_NAME}"
      JWT_KEY: "${JWT_KEY}"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  redis:
    container_name: auth-redis
    image: redis:latest
    networks:
      - auth
    ports:
      - 6379:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  db:
    image: postgres:16
    container_name: auth-postgres
    networks:
      - auth
    restart: always
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${MASTER_USER}"
      POSTGRES_PASSWORD: "${MASTER_PASS}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 5s

networks:
  auth: