[package]
name = "auto-encryption"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.90", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.20.10"
encryption-libs = { path = "../encryption-libs" }

[lib]
proc-macro = true
