[package]
name = "encryption-libs"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = { version = "0.15.7"}
darling = "0.20.10"
quote = "1.0"
proc-macro2 = "1.0.92"
aes-gcm = "0.10.3"
hex = "0.4.3"